 # Amazon logo = '.a-icon.a-icon-logo'
 # Create account = 'h1.a-spacing-small'
 # Your name field = 'ap_customer_name'
 # Email = 'ap_email'
 # Password = 'ap_password'
 # Alert content = 'div.auth-inlined-information-message.a-alert-inline-info div.a-alert-content'
 # Re-eneter password = 'ap_password_check'
 # Continue = 'continue'
 # Conditions of use = 'a[href*="ap_register_notification_condition_of_use"]'
 # Privacy notice = 'a[href*="ap_register_notification_privacy_notice"]'
 # Sign in = 'a[href*="signin"]'